spring:
  application:
    name: user-service
server:
  port: 8080
resilience4j:
  circuitbreaker:
    instances:
      product-service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
management:
  endpoints:
    web:
      exposure:
        include: '*'        